name: sync

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB || github.token }}
  token: ${{ secrets.TOKEN_GITHUB || github.token }}
  GH_TOKEN: ${{ github.token }}
  GITHUB_REPO: ${{github.repo}}
  WORKER_ORG: laciferin
  # WORKER_NAME: ${{ github.workflow }}-${{github.ref}}

jobs:
  sync-across-dapps:
    if: ${{github.repository}}=="antFame/ant"

    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        org: ["colony2024"] #colony2023
        repo: ["a"]

    runs-on: ubuntu-latest
    env:
      REPO: ${{matrix.org}}/${{matrix.repo}}
    steps:
      - name: Set up Git credentials
        run: |
          git config --global user.name Nasfame
          git config --global user.email "laciferin@gmail.com"
          git config --global credential.helper '!f() { echo "username=Nasfame\npassword=$GITHUB_TOKEN"; }; f'
          git config --global push.autoSetupRemote true
          git config --global push.default matching
          git config --global alias.tags 'tag -n99'

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Create repo
        continue-on-error: true
        run: gh repo create ${{env.REPO}} --public --confirm

      - name: Set secrets
        run: |
          gh secret set WORKER_ORG --org ${{matrix.org}} --repos ${{env.REPO}} --body ${{ env.WORKER_ORG }}
          gh secret set TOKEN_GITHUB --org ${{matrix.org}} --repos ${{env.REPO}} --body ${{ env.GITHUB_TOKEN }}

      # set gh auth
      # gh create public repo in a step
      # gh add secret WORKER_ORG secret to the repo
      # gh add secret TOKEN_GITHUB in another step
